name: lettutor
description: A mock-up one-on-one learning project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  intl: ^0.17.0
  provider: ^5.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  flutter_tags: ^0.4.9+1
  country_code_picker: ^2.0.2
  flutter_rating_bar: ^4.0.0
  syncfusion_flutter_datepicker: ^19.3.44
  syncfusion_flutter_calendar: ^19.3.44
  timeago: ^3.1.0
  flutter_countdown_timer: ^4.1.0
  email_validator: ^2.0.1
  json_annotation: ^4.3.0
  flutter_redux: ^0.8.2
  redux: ^5.0.0
  image_picker: ^0.8.4+4
  video_player: ^2.2.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo_with_text.svg
    - assets/images/ic_us_flag.svg
    - assets/images/ic_vn_flag.svg
    - assets/images/hero_pic.png
    - assets/images/sign_in.png
    - assets/images/google_icon.svg
    - assets/images/facebook_icon.svg
    - assets/images/history_view_icon.svg
    - assets/images/schedule_view_icon.svg
    - assets/images/course_view_icon.svg
    - assets/tutors_dummy.json
    - assets/booking_dummy.json
    - assets/total_hour_dummy.json
    - assets/schedule_calendar_dummy.json
    - assets/user_dummy.json
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
          style: normal
        - asset: assets/fonts/Poppins-Italic.otf
          style: italic
        - asset: assets/fonts/Poppins-Bold.otf
        - asset: assets/fonts/Poppins-Thin.otf
